# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x9hWxA_j5VR-MIjjbM23WZIZYoyL2y8q
"""

score=input().split()
count=0
for i in score:
  if int(i) < 60:
    count=count+1
print('不及格人數:',count)