# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SPhSPlkWEmuEx48B4dtjEgwoAJN5gshM
"""

Score=input().split()
count=0
for i in Score:
  if int(i)<60:
    count=count+1
print("不及格人數:",count)

sum=0
for j in Score:
  sum=sum+int(j)
avg=sum/len(Score)
print('平均分:',avg)